#-------------------------------
# /關於 相關設定：
about:
  # 標題使用的 emoji。
  emoji: "🔰"

  # 機器人的暱稱（將用於部分指令，請勿使用大寫英文或空格）
  botNickname: "bot"
  
  # 機器人的介紹
  introduce: "みやこ機器人第三代！\n這是一個基於 discord.js 集合許多功能的綜合型機器人，\n本專案目前仍在積極開發中！"
  
  # 服務提供者，請填入您的 Discord 數字 ID
  provider: " "

  # 專案連結
  repository: "https://github.com/miguotw/NewIsland-DCB"


#-------------------------------
# /延遲 相關設定：
ping:
  emoji: "🏓"


#-------------------------------
# /與 AI 聊天 相關設定：
NewIslandChat:
  emoji: "🗨️"
  
  # 允許擁有該身分組的用戶創建可供交互的按鈕
  admin: " "
  
  # 與 AI 進行對話的預設提示詞，允與用戶在之後的對話中更改提示詞
  prompt: " "
  
  # 發送給 AI 的對話內容的最大長度，從最後的對話開始計算，每 1 輪問答為 1 個 length。
  # 假設 mexLength 為 20，則最後 40 句對話內容將被發送給 AI 進行對話。
  # 此處的數值不宜過大或過小，過大可能會導致 AI 回答不夠準確的同時還浪費 tokens，過小可能會導致 AI 回答過於簡單。
  mexLength: 5
  
  # 透過 OpenAI API Library 進行交互，原則上可支援使用此 API 進行交互的語言模型
  models:
    name: "google/gemma-3-27b-it:free"
    baseURL: "https://openrouter.ai/api/v1"
    apiKey: " "


#-------------------------------
# /麥塊 相關設定：
minecraft:
  emoji: "🧱"

  #預設列表中的伺服器名稱與 IP，可繼續向下延伸，最多支援 25 個
  defaultServer:
    Hypixel: "mc.hypixel.net"
